### ISSUE TITLE
[AVCaptureSession startRunning] startRunning may not be called between calls to beginConfiguration and commitConfiguration'

### ISSUE THREAD

**Issue by priyankgandhi0** [quickpose/quickpose-ios-sdk#10]
*** Terminating app due to uncaught exception 'NSGenericException', reason: '*** -[AVCaptureSession startRunning] startRunning may not be called between calls to beginConfiguration and commitConfiguration'

![Screenshot 2023-12-05 at 12 33 10 PM](https://github.com/quickpose/quickpose-ios-sdk/assets/13184098/f8709781-f157-4376-9459-9cbc457dc7c1)

Hi there 

Any anyone know why the app crashes sometimes and gets this crash error?

If anyone knows please suggest to me how can i fix this issue 

Thank you in advance

**Comment by pablonosh** [comment]
It looks like you're starting the same camera twice, or during a config change.

**Comment by priyankgandhi0** [comment]
We have set the camera in the subview on the main screen, so features are the camera is subviews hide or show and closed also
can you please check my attachment
![Screenshot 2023-12-05 at 3 17 17 PM](https://github.com/quickpose/quickpose-ios-sdk/assets/13184098/d75aaf97-a97a-47b5-a8fc-bc4bd349b3e7)

**Comment by priyankgandhi0** [comment]
![Screenshot 2023-12-07 at 5 22 17 PM](https://github.com/quickpose/quickpose-ios-sdk/assets/13184098/e1d8a8c8-f0b6-4e48-a384-22e372bb80bd)

When I checked and same test case in your provided demo also got the same crash issue. I will describe the steps here.

**Step 1**
 We added a New Screen ahead in the quick pose camera screen and then Went to the camera screen and went back to again same process we had done more times then suddenly app crashed and got this error below

** Terminating app due to uncaught exception 'NSGenericException', reason: '** -[AVCaptureSession startRunning] startRunning may not be called between calls to beginConfiguration and commitConfiguration'

**Step 2**

We have added a new view screen after the quick pose camera go ahead click the next screen and come back again same process go next screen and come back again camera screen app crashes and got an error


*If anyone knows please suggest to me how can I fix this issue*

Thank you in advance

**Comment by priyankgandhi0** [comment]
Any solution for this above issue? Please let me know ASAP

**Comment by pablonosh** [comment]
Hi

We reached out via our support email last week, this is likely an issue specific to how your code is showing and hiding the camera view. With camera use you have to be careful when hiding views to ensure the camera is only accessed once. 

Through our support process we can organise a remote support call where we can debug this issue together, and work on your code which would allow this feature but this would be beyond the community support level we provide on github.

Please reply to our support email directly, or on info@quickpose.ai

Thanks
Peter

**Comment by priyankgandhi0** [comment]
We have already contacted email support and they will ask if you want integration support or to resolve the issue then you need to first payment.

**Comment by priyankgandhi0** [comment]
![Screenshot 2023-12-12 at 9 35 27 AM](https://github.com/quickpose/quickpose-ios-sdk/assets/13184098/beddf811-4186-4df7-baad-f7c6f58ecf9c)
![Screenshot 2023-12-12 at 9 35 32 AM](https://github.com/quickpose/quickpose-ios-sdk/assets/13184098/96819e75-5d84-4bf5-91e5-09d3968548cd)

The above pictures are my sample code when I come back to the screen and then crash on this **try? camera?.start(delegate: quickPose)** inside library code crash line is **session.startRunning()** this our crash test case can you please check out this

**Comment by pablonosh** [comment]
Closing this as it's specific to the codebase we reviewed.
In short it's advised to not re-create the camera object and quickpose regularly, keep hold of the object.
