### ISSUE TITLE
Add bundle version information to QuickPoseMP.framework

### ISSUE THREAD

**Issue by AlexExcellence** [quickpose/quickpose-ios-sdk#11]
Hi,
Since Xcode 15, Apple requires Frameworks to include bundle version information in the Info.plist files (https://forums.developer.apple.com/forums/thread/738351?answerId=774763022#774763022).

Consequently, it is currently impossible to archive apps using the QuickPoseMP.framework. To fix that, the [CFBundleVersion](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion) and the [CFBundleShortVersionString](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring) need to be included in the Info.plist file of the QuickPoseMP.framework.

**Comment by filipljubicic** [comment]
Hi AlexExcellence,

Thank you for sharing this with us. Just wanted to check did this happen to you in the latest version of QuickPose?

**Comment by AlexExcellence** [comment]
That was the issue, thank you!
