### ISSUE TITLE
Impossibility to build on Simulator when library is used

### ISSUE THREAD

**Issue by TkachenkoBogdan** [quickpose/quickpose-ios-sdk#16]
Hello, I have checked the readme and see that the simulator is not supported currently.

It does not make any sense to test/use ai features on simulator.  However, we would like for our app as a whole to continue running on iOS simulator for developer purposes. 

The issue lies in fact that any simulator build for a target that depends on the framework is going to fail.

Maybe you someone is aware of conditional solutions for this issue? Are there any hacks that will allow skipping importing the framewors and stubbing its APIs for simulator builds?

**Comment by pablonosh** [comment]
This has been addressed in 1.2.9, for both SPM and cocoapods.

Long term there is a potential of injecting test scenarios, but we're leaving as stubs for the simulator for now.

It requires no simulator macros in your apps, so check the basic demo SampleApp if you have an issues your side:
https://github.com/quickpose/quickpose-ios-sdk/tree/main/SampleApps/SwiftUI/BasicDemo
