### ISSUE TITLE
Please stop scraping/spamming GitHub email addresses

### ISSUE THREAD

**Issue by olirice** [quickpose/quickpose-ios-sdk#4]
See [GitHub TOS](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies#4-spam-and-inauthentic-activity-on-github)

<img width="940" alt="Screenshot 2023-06-01 at 12 47 10 PM" src="https://github.com/quickpose/quickpose-ios-sdk/assets/12958657/20507644-ef4e-4300-8b27-63ba436a6094">

**Comment by filipljubicic** [comment]
Hi Oliver, 

Thank you for bringing this to our attention. We've spoken to Kevin about this and have taken action to stop this from happening again. At the same time, we reviewed his outreach practices to understand why he did something he wasn't asked to do.
