### ISSUE TITLE
[Q] How to use this package with cocoapods

### ISSUE THREAD

**Issue by hasn-ab** [quickpose/quickpose-ios-sdk#5]
I am looking to integrate this SDK with react native. But react native currently uses Cocoapods.
Adding this as a package ie File -> Add Packages and then adding repo link does not work.

The app runs but I get following error and screen is blank:

`objc[19346]: Class AppDelegate is implemented in both /Users/name/Library/Developer/Xcode/DerivedData/App-fkvazkoxdzkftrfgowaowxxijvqj/Build/Products/Debug-iphonesimulator/QuickPoseMP.framework/QuickPoseMP (0x117cb3e88) and /Users/name/Library/Developer/CoreSimulator/Devices/91A0E37E-3950-4B27-91AE-ABE2376094C9/data/Containers/Bundle/Application/9BC68EDF-7E2C-4278-AAAF-078D0385AB61/App.app/App (0x10fcb5510). One of the two will be used. Which one is undefined.`

I guess that is because swift packages can not be used with cocoapods?

**Comment by pablonosh** [comment]
QuickPose now officially supports Cocoapods - please see README section: https://github.com/quickpose/quickpose-ios-sdk#cocoapods and Cocoapod Sample App for more details. 

I'll close this for now, but please re-open if you have any further issues.

**Comment by hasn-ab** [comment]
@pablonosh I am still getting this issue after installing the SDK with Cocoapods.

**Comment by hasn-ab** [comment]
These are the logs that I get: 

```
objc[4722]: Class VideoWriter is implemented in both /System/Library/PrivateFrameworks/AutoLoop.framework/
AutoLoop (0x1e4f8e570) and /private/var/containers/Bundle/Application/0DE20910-CCCD-417C-AE9E-02C1D431D797/My
App.app/Frameworks/QuickPoseMP.framework/QuickPoseMP (0x10d063b20). 
One of the two will be used. Which one is undefined.

objc[4722]: Class AppDelegate is implemented in both /private/var/containers/Bundle/Application/0DE20910-CCCD-
417C-AE9E-02C1D431D797/MyApp.app/Frameworks/QuickPoseMP.framework/QuickPoseMP (0x10d063c38) and /private/var/c
ontainers/Bundle/Application/0DE20910-CCCD-417C-AE9E-02C1D431D797/Motics.app/MyApp (0x103f5d930). One of the
two will be used. Which one is undefined.
```

**Comment by pablonosh** [comment]
This looks like Mediapipe is adding two classes without the objective-c standard protective namespace prefix. 
We don't use VideoWriter or AppDelegate so these can safely be replaced, but I suspect AppDelegate is used by React-Native and so this is causing a problem.

I'm looking into changing Mediapipe to avoid these issues, but this will take some time. In the short term is it possible to rename the AppDelegate class in your app?

**Comment by pablonosh** [comment]
Ok, I've slimmed down our MP framework, so the latest commit to main will have a slimmer Mediapipe framework.

Can you update and use this? Remember to clear your caches etc.

**Comment by hasn-ab** [comment]
Thanks @pablonosh, will look into these changes and update.
