### ISSUE TITLE
How to Add New Exercise?

### ISSUE THREAD

**Issue by herol-gl** [quickpose/quickpose-ios-sdk#8]
Thanks for the great product. Is it possible to add new exercise by myself? Any documentation that I can refer to?

**Comment by pablonosh** [comment]
Thanks for getting in touch, and glad you like quickpose. Which exercise did you have in mind?

**Comment by herol-gl** [comment]
@pablonosh 
Plenty of pilates exercises such as the one on this book cover.
![pilates](https://github.com/quickpose/quickpose-ios-sdk/assets/43488956/7bbda72a-d3da-4822-bc8b-615cc100b9ba)

**Comment by herol-gl** [comment]
@pablonosh 
Could you share an example how you detect the motion of an exercise, like .fitness(.vUps)?
Thank you.

**Comment by herol-gl** [comment]
@pablonosh 
Any updates?

**Comment by pablonosh** [comment]
Hi
The detection of exercises are developed by our team in-house. So the best way of getting new features inside the sdk is to checkout our development offerings https://quickpose.ai/full-stack/
